#!/usr/bin/env bash
# AriaNg_aria2_File_Browser_install.sh
set -Eeuo pipefail

# AriaNg + aria2 + File Browser installer
# - AriaNg / aria2 page: host port 26080
# - File Browser page: host port 26081
#
# The AriaNg container below is hurlenko/aria2-ariang, which serves AriaNg
# and reverse-proxies /jsonrpc and /rpc to aria2 inside the same container.
# This keeps the aria2 JSON-RPC endpoint on the same public port as AriaNg.

APP_DIR="${APP_DIR:-/root/AriaNg_aria2_d}"
DATA_DIR="${DATA_DIR:-/data/AriaNg_aria2_d}"

TZ="${TZ:-Asia/Taipei}"
PUID="${PUID:-1000}"
PGID="${PGID:-1000}"

ARIA_SERVICE="ariang_aria2"
ARIA_CONTAINER="ariang_aria2"
ARIA_IMAGE="${ARIA_IMAGE:-hurlenko/aria2-ariang:latest}"
ARIANG_WEBUI_PORT="${ARIANG_WEBUI_PORT:-26080}"
ARIA2_BT_PORT="${ARIA2_BT_PORT:-26881}"
ARIANG_USERNAME="${ARIANG_USERNAME:-q}"
ARIANG_PASSWORD="${ARIANG_PASSWORD:-ofwardao@gmail.com}"
ARIA2_RPC_SECRET="${ARIA2_RPC_SECRET:-${ARIANG_PASSWORD}}"
ARIA2_CONFIG_DIR="${ARIA2_CONFIG_DIR:-${DATA_DIR}/aria2/config}"
ARIA2_DOWNLOAD_DIR="${ARIA2_DOWNLOAD_DIR:-${DATA_DIR}/downloads}"

FB_SERVICE="filebrowser"
FB_CONTAINER="filebrowser"
FB_IMAGE="${FB_IMAGE:-filebrowser/filebrowser:s6}"
FB_WEBUI_PORT="${FB_WEBUI_PORT:-26081}"
FB_USERNAME="${FB_USERNAME:-q}"
FB_PASSWORD="${FB_PASSWORD:-ofwardao@gmail.com}"

# Default File Browser root is downloads only.
FB_ROOT_DIR="${FB_ROOT_DIR:-${DATA_DIR}/downloads}"
FB_DB_DIR="${FB_DB_DIR:-${DATA_DIR}/filebrowser/database}"
FB_CONFIG_DIR="${FB_CONFIG_DIR:-${DATA_DIR}/filebrowser/config}"

COMPOSE_FILE="${APP_DIR}/docker-compose.yml"
PASSWD_FILE="${APP_DIR}/passwd.txt"
LOG_FILE="${APP_DIR}/install.log"

mkdir -p "$APP_DIR"
touch "$LOG_FILE"

log() {
	echo "[$(date '+%F %T')] $*" | tee -a "$LOG_FILE"
}

die() {
	echo "ERROR: $*" | tee -a "$LOG_FILE" >&2
	exit 1
}

if [[ "${EUID}" -ne 0 ]]; then
	die "Run this script as root."
fi

install_deps() {
	log "Checking dependencies..."

	local need_apt=0
	for bin in curl docker; do
		if ! command -v "$bin" >/dev/null 2>&1; then
			need_apt=1
		fi
	done

	if [[ "$need_apt" -eq 1 ]]; then
		if command -v apt-get >/dev/null 2>&1; then
			log "Installing curl, Docker, and Docker Compose plugin with apt..."
			apt-get update
			apt-get install -y curl docker.io docker-compose-plugin
		else
			die "Missing curl/docker and apt-get is not available. Install them first."
		fi
	fi

	if ! docker compose version >/dev/null 2>&1 && ! command -v docker-compose >/dev/null 2>&1; then
		if command -v apt-get >/dev/null 2>&1; then
			log "Installing Docker Compose..."
			apt-get update
			apt-get install -y docker-compose-plugin || apt-get install -y docker-compose
		else
			die "Docker Compose is missing."
		fi
	fi

	systemctl enable --now docker >/dev/null 2>&1 || true
}

set_compose_cmd() {
	if docker compose version >/dev/null 2>&1; then
		COMPOSE_CMD=(docker compose)
	elif command -v docker-compose >/dev/null 2>&1; then
		COMPOSE_CMD=(docker-compose)
	else
		die "Docker Compose is not available."
	fi
}

compose() {
	(cd "$APP_DIR" && "${COMPOSE_CMD[@]}" -f "$COMPOSE_FILE" "$@")
}

get_public_ip() {
	local url ip
	local urls=(
		"https://ip.sb"
		"https://api.ipify.org"
		"https://ifconfig.me/ip"
		"https://icanhazip.com"
		"https://ipinfo.io/ip"
	)

	for url in "${urls[@]}"; do
		ip="$(curl -4fsSL --max-time 8 "$url" 2>/dev/null | tr -d '[:space:]' || true)"
		if [[ "$ip" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]] && [[ ! "$ip" =~ ^127\. ]]; then
			echo "$ip"
			return 0
		fi
	done

	ip="$(hostname -I 2>/dev/null | awk '{print $1}' || true)"
	if [[ -n "$ip" && ! "$ip" =~ ^127\. ]]; then
		echo "$ip"
		return 0
	fi

	echo "YOUR_PUBLIC_IP"
}

make_dirs() {
	log "Creating directories..."

	mkdir -p \
		"$APP_DIR" \
		"$ARIA2_CONFIG_DIR" \
		"$ARIA2_DOWNLOAD_DIR" \
		"$FB_ROOT_DIR" \
		"$FB_DB_DIR" \
		"$FB_CONFIG_DIR"

	chmod 700 "$APP_DIR"
	chmod -R 775 "$DATA_DIR"
	chown -R "${PUID}:${PGID}" "$DATA_DIR" >/dev/null 2>&1 || true
}

write_aria2_conf() {
	local conf="${ARIA2_CONFIG_DIR}/aria2.conf"
	local session="${ARIA2_CONFIG_DIR}/aria2.session"
	local dht4="${ARIA2_CONFIG_DIR}/dht.dat"
	local dht6="${ARIA2_CONFIG_DIR}/dht6.dat"

	log "Writing aria2 config to ${conf}..."

	mkdir -p "$ARIA2_CONFIG_DIR" "$ARIA2_DOWNLOAD_DIR"
	touch "$session" "$dht4" "$dht6"

	cat >"$conf" <<EOF_ARIA2
# aria2.conf generated by AriaNg_aria2_File_Browser_install.sh

# Download directory inside the aria2 container.
dir=/aria2/data

# Resume / session persistence.
continue=true
input-file=/aria2/conf/aria2.session
save-session=/aria2/conf/aria2.session
save-session-interval=10
force-save=true

# RPC. The public browser entry point is AriaNg's /jsonrpc on port ${ARIANG_WEBUI_PORT};
# internally aria2 listens on 6800 and Caddy reverse-proxies /jsonrpc and /rpc.
enable-rpc=true
rpc-listen-all=true
rpc-listen-port=6800
rpc-allow-origin-all=true

# Download performance.
max-concurrent-downloads=5
max-connection-per-server=10
split=10
min-split-size=10M
max-overall-download-limit=0
max-download-limit=0
max-overall-upload-limit=0
max-upload-limit=0
lowest-speed-limit=0
file-allocation=none
disk-cache=64M

# File behavior.
allow-overwrite=false
auto-file-renaming=true
content-disposition-default-utf8=true

# BitTorrent / magnet support.
listen-port=${ARIA2_BT_PORT}
dht-listen-port=${ARIA2_BT_PORT}
enable-dht=true
enable-dht6=false
enable-peer-exchange=true
bt-enable-lpd=true
bt-save-metadata=true
bt-load-saved-metadata=true
follow-torrent=true
seed-ratio=1.0

# DHT files.
dht-file-path=/aria2/conf/dht.dat
dht-file-path6=/aria2/conf/dht6.dat

# Logging.
console-log-level=notice
EOF_ARIA2

	chown -R "${PUID}:${PGID}" "$ARIA2_CONFIG_DIR" "$ARIA2_DOWNLOAD_DIR" >/dev/null 2>&1 || true
}

write_compose_file() {
	log "Writing ${COMPOSE_FILE}..."

	cat >"$COMPOSE_FILE" <<YAML
services:
  ${ARIA_SERVICE}:
    image: ${ARIA_IMAGE}
    container_name: ${ARIA_CONTAINER}
    restart: unless-stopped
    stop_grace_period: "10s"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - RPC_SECRET=${ARIA2_RPC_SECRET}
      - EMBED_RPC_SECRET=true
      - BASIC_AUTH_USERNAME=${ARIANG_USERNAME}
      - BASIC_AUTH_PASSWORD=${ARIANG_PASSWORD}
      - ARIA2RPCPORT=${ARIANG_WEBUI_PORT}
    volumes:
      - ${ARIA2_DOWNLOAD_DIR}:/aria2/data
      - ${ARIA2_CONFIG_DIR}:/aria2/conf
    ports:
      - "${ARIANG_WEBUI_PORT}:8080"
      - "${ARIA2_BT_PORT}:${ARIA2_BT_PORT}"
      - "${ARIA2_BT_PORT}:${ARIA2_BT_PORT}/udp"
    networks:
      - download_net

  ${FB_SERVICE}:
    image: ${FB_IMAGE}
    container_name: ${FB_CONTAINER}
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${FB_ROOT_DIR}:/srv
      - ${FB_DB_DIR}:/database
      - ${FB_CONFIG_DIR}:/config
    ports:
      - "${FB_WEBUI_PORT}:80"
    networks:
      - download_net

networks:
  download_net:
    name: download_net
YAML

	chmod 600 "$COMPOSE_FILE"
}

wait_for_http() {
	local name="$1"
	local port="$2"
	local path="${3:-/}"
	local auth_args=()

	if [[ "${4:-}" == "auth" ]]; then
		auth_args=(-u "${ARIANG_USERNAME}:${ARIANG_PASSWORD}")
	fi

	log "Waiting for ${name} on host port ${port}${path}..."

	for _ in $(seq 1 120); do
		local code
		code="$(curl -sS --max-time 4 "${auth_args[@]}" -o /dev/null -w '%{http_code}' "http://localhost:${port}${path}" || true)"
		if [[ "$code" == "200" || "$code" == "301" || "$code" == "302" || "$code" == "401" || "$code" == "403" ]]; then
			log "${name} responded with HTTP ${code}."
			return 0
		fi
		sleep 1
	done

	die "${name} did not become reachable on host port ${port}${path}."
}

verify_ariang_auth() {
	local code

	log "Verifying AriaNg basic-auth login..."
	code="$(curl -sS --max-time 8 -u "${ARIANG_USERNAME}:${ARIANG_PASSWORD}" -o /dev/null -w '%{http_code}' "http://localhost:${ARIANG_WEBUI_PORT}/" || true)"

	if [[ "$code" != "200" && "$code" != "301" && "$code" != "302" ]]; then
		docker logs "$ARIA_CONTAINER" 2>&1 | tail -n 120 | tee -a "$LOG_FILE" || true
		die "AriaNg authenticated page check failed. HTTP code: ${code}"
	fi

	log "AriaNg basic-auth login works."
}

verify_aria2_rpc() {
	local payload response

	log "Verifying aria2 JSON-RPC through AriaNg /jsonrpc..."
	payload='{"jsonrpc":"2.0","id":"aria2-test","method":"aria2.getVersion","params":["token:'"${ARIA2_RPC_SECRET}"'"]}'

	response="$(curl -sS --max-time 10 \
		-u "${ARIANG_USERNAME}:${ARIANG_PASSWORD}" \
		-H 'Content-Type: application/json' \
		--data "$payload" \
		"http://localhost:${ARIANG_WEBUI_PORT}/jsonrpc" || true)"

	if [[ "$response" != *'"result"'* || "$response" != *'"version"'* ]]; then
		docker logs "$ARIA_CONTAINER" 2>&1 | tail -n 160 | tee -a "$LOG_FILE" || true
		echo "aria2 RPC response: ${response}" | tee -a "$LOG_FILE"
		die "aria2 JSON-RPC verification failed."
	fi

	log "aria2 JSON-RPC works."
}

fb_cli() {
	docker run --rm \
		-v "${FB_ROOT_DIR}:/srv" \
		-v "${FB_DB_DIR}:/database" \
		-v "${FB_CONFIG_DIR}:/config" \
		--entrypoint filebrowser \
		"$FB_IMAGE" \
		-d /database/filebrowser.db "$@"
}

configure_filebrowser() {
	log "Configuring File Browser static account..."

	mkdir -p "$FB_ROOT_DIR" "$FB_DB_DIR" "$FB_CONFIG_DIR"
	chown -R "${PUID}:${PGID}" "$FB_ROOT_DIR" "$FB_DB_DIR" "$FB_CONFIG_DIR" >/dev/null 2>&1 || true

	if [[ ! -f "${FB_DB_DIR}/filebrowser.db" ]]; then
		fb_cli config init \
			--address 0.0.0.0 \
			--port 80 \
			--root /srv \
			--minimumPasswordLength 1
	else
		fb_cli config set \
			--address 0.0.0.0 \
			--port 80 \
			--root /srv \
			--minimumPasswordLength 1
	fi

	if fb_cli users update "$FB_USERNAME" \
		--password "$FB_PASSWORD" \
		--perm.admin \
		--perm.create \
		--perm.delete \
		--perm.download \
		--perm.modify \
		--perm.rename \
		--perm.share >/dev/null 2>&1; then
		log "Updated existing File Browser user '${FB_USERNAME}'."
	else
		fb_cli users add "$FB_USERNAME" "$FB_PASSWORD" \
			--perm.admin \
			--perm.create \
			--perm.delete \
			--perm.download \
			--perm.modify \
			--perm.rename \
			--perm.share
		log "Created File Browser user '${FB_USERNAME}'."
	fi

	if [[ "$FB_USERNAME" != "admin" ]]; then
		fb_cli users rm admin >/dev/null 2>&1 || true
	fi

	chown -R "${PUID}:${PGID}" "$FB_ROOT_DIR" "$FB_DB_DIR" "$FB_CONFIG_DIR" >/dev/null 2>&1 || true
}

write_passwd_file() {
	local public_host="$1"
	local ariang_url="http://${public_host}:${ARIANG_WEBUI_PORT}/"
	local aria2_rpc_url="http://${public_host}:${ARIANG_WEBUI_PORT}/jsonrpc"
	local fb_url="http://${public_host}:${FB_WEBUI_PORT}/"

	log "Writing credentials to ${PASSWD_FILE}..."

	cat >"$PASSWD_FILE" <<EOF_PASSWD
AriaNg + aria2
URL: ${ariang_url}
Username: ${ARIANG_USERNAME}
Password: ${ARIANG_PASSWORD}
WebUI port: ${ARIANG_WEBUI_PORT}
aria2 JSON-RPC URL: ${aria2_rpc_url}
aria2 JSON-RPC secret/token: ${ARIA2_RPC_SECRET}
aria2 BT TCP port: ${ARIA2_BT_PORT}
aria2 BT UDP port: ${ARIA2_BT_PORT}
Download dir: ${ARIA2_DOWNLOAD_DIR}
Config dir: ${ARIA2_CONFIG_DIR}

File Browser
URL: ${fb_url}
Username: ${FB_USERNAME}
Password: ${FB_PASSWORD}
WebUI port: ${FB_WEBUI_PORT}
Root dir: ${FB_ROOT_DIR}

Docker
Compose file: ${COMPOSE_FILE}
AriaNg + aria2 container: ${ARIA_CONTAINER}
File Browser container: ${FB_CONTAINER}
Docker network: download_net

Host paths
App dir: ${APP_DIR}
Data dir: ${DATA_DIR}
aria2 config dir: ${ARIA2_CONFIG_DIR}
aria2 downloads dir: ${ARIA2_DOWNLOAD_DIR}
File Browser root dir: ${FB_ROOT_DIR}
File Browser database dir: ${FB_DB_DIR}
File Browser config dir: ${FB_CONFIG_DIR}

Internal Docker URLs
AriaNg: http://${ARIA_SERVICE}:8080
aria2 JSON-RPC through AriaNg container: http://${ARIA_SERVICE}:8080/jsonrpc
File Browser: http://${FB_SERVICE}:80
EOF_PASSWD

	chmod 600 "$PASSWD_FILE"
}

main() {
	install_deps
	set_compose_cmd
	make_dirs
	write_aria2_conf
	write_compose_file

	log "Stopping/removing old containers with the same names while keeping host data..."
	docker rm -f "$ARIA_CONTAINER" >/dev/null 2>&1 || true
	docker rm -f ariang aria2 aria2-pro aria2_ariang >/dev/null 2>&1 || true
	docker rm -f "$FB_CONTAINER" >/dev/null 2>&1 || true

	log "Pulling images..."
	compose pull

	configure_filebrowser

	log "Starting AriaNg + aria2 and File Browser..."
	compose up -d

	wait_for_http "AriaNg WebUI" "$ARIANG_WEBUI_PORT" "/"
	verify_ariang_auth
	verify_aria2_rpc
	wait_for_http "File Browser" "$FB_WEBUI_PORT" "/"

	local public_host
	public_host="$(get_public_ip)"
	write_passwd_file "$public_host"

	log "Done."
	echo
	echo "============================================================"
	echo "AriaNg + aria2 + File Browser installed."
	echo
	echo "Open:"
	echo "  AriaNg + aria2: http://${public_host}:${ARIANG_WEBUI_PORT}/"
	echo "  File Browser:  http://${public_host}:${FB_WEBUI_PORT}/"
	echo
	echo "AriaNg basic-auth login:"
	echo "  Username: ${ARIANG_USERNAME}"
	echo "  Password: ${ARIANG_PASSWORD}"
	echo
	echo "aria2 RPC:"
	echo "  URL:    http://${public_host}:${ARIANG_WEBUI_PORT}/jsonrpc"
	echo "  Token:  ${ARIA2_RPC_SECRET}"
	echo
	echo "File Browser login:"
	echo "  Username: ${FB_USERNAME}"
	echo "  Password: ${FB_PASSWORD}"
	echo
	echo "Credentials saved at:"
	echo "  ${PASSWD_FILE}"
	echo
	echo "Show credentials later:"
	echo "  cat ${PASSWD_FILE}"
	echo
	echo "Downloads:"
	echo "  ${ARIA2_DOWNLOAD_DIR}"
	echo "============================================================"
}

main "$@"
