version: '3'
services:
  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: mariadb
    environment:
      - PUID=1000                     # Replace with your user ID
      - PGID=1000                     # Replace with your group ID
      - TZ=Etc/UTC
      - MYSQL_ROOT_PASSWORD=rootpass  # Replace with a secure root password
      - MYSQL_DATABASE=bookstackdb
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=bookstackpass  # Replace with a secure database password
    volumes:
      - ./mariadb/config:/config
    restart: unless-stopped

  bookstack:
    image: lscr.io/linuxserver/bookstack:latest
    container_name: bookstack
    depends_on:
      - mariadb
    environment:
      - PUID=1000                     # Replace with your user ID
      - PGID=1000                     # Replace with your group ID
      - TZ=Etc/UTC
      - APP_URL=http://hk.zhulei.eu.org:8081 # Replace with your actual URL if accessible externally
      - APP_KEY=base64:cln5Y03tMyjcni+1WQBxSC0pY6u6bGX+iJtyGOu1dWc= #Leave empty to auto-generate or provide your own
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_DATABASE=bookstackdb
      - DB_USERNAME=bookstack
      - DB_PASSWORD=bookstackpass     # Must match the password set in the mariadb service
      - QUEUE_CONNECTION=database     # Enables async actions like email sending
    volumes:
      - ./bookstack/config:/config
    ports:
      - 8081:80
    restart: unless-stopped

