version: '3.8'
services:
  markdown-app:
    image: oklove/upload_folder
    restart: unless-stopped
    ports:
      - "7777:7777"   
    volumes:
      - /data/upload_folder:/data/upload_folder
        # Map the current directory on the host to /usr/src/app in the container
