version: '3.8'

services:
  markdown-app:
    image: oklove/markdown:latest
    hostname: a7
    restart: unless-stopped
    ports:
      - "177:177"
    volumes:
      - /data:/data
    environment:
      - USERNAME=1
      - PASSWORD=1
